### ISSUE TITLE
Summarize has abnormal behaviour with some clargs configurations

### ISSUE THREAD

**Issue by jlandercy** [jlandercy/airpy#27]
There is a bad mapping in `summarize.py`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/summarize.py", line 149, in <module>
    main(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/clargs.py", line 30, in inner
    func = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/summarize.py", line 65, in main
    data = datastore.getDataFrame(path=dspath, node=nkey, indexkeys=unode['indexkeys'])
TypeError: getDataFrame() got an unexpected keyword argument 'indexkeys'
```

**Comment by jlandercy** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/summarize.py", line 149, in <module>
    main(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/clargs.py", line 30, in inner
    func = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/summarize.py", line 108, in main
    clusterSlices = index.getLevelIndexSlices(data.columns, ckey)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/report/index.py", line 41, in getLevelIndexSlices
    lidx = index.names.index(lkey)
ValueError: 'sitekey' is not in list

```

**Comment by jlandercy** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/summarize.py", line 149, in <module>
    main(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/clargs.py", line 30, in inner
    func = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/summarize.py", line 104, in main
    for ckey in unode['clusters']:
TypeError: 'NoneType' object is not iterable
```

**Comment by jlandercy** [comment]
` MainThread      airpy/schema/query.py   getDataFrame    ERROR   Cannot index/pivot dataframe: name 'node' is not defined`

**Comment by jlandercy** [comment]
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pandas/indexes/base.py", line 2134, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 139, in pandas.index.IndexEngine.get_loc (pandas/index.c:4443)
  File "pandas/index.pyx", line 161, in pandas.index.IndexEngine.get_loc (pandas/index.c:4289)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13733)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13687)
KeyError: 'channelid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/summarize.py", line 157, in <module>
    main(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/clargs.py", line 30, in inner
    func = f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/summarize.py", line 70, in main
    data = datastore.getDataset(path=dspath, datanode=nkey, granulityid=unode['granulityid'], indexkeys=unode['indexkeys'], sorted=True, continuity=True, extrarow=True)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/schema/datastore.py", line 38, in getDataset
    d = dataset.dataset(data, meta, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/scientific/dataset.py", line 59, in __init__
    nmeta = dataset.prepareMeta(data, meta)
  File "/usr/local/lib/python3.5/dist-packages/airpy-1.525-py3.5.egg/airpy/scientific/dataset.py", line 79, in prepareMeta
    nmeta = meta.set_index(didx.names, drop=False)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2917, in set_index
    level = frame[col]._values
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals.py", line 3541, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.5/dist-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 139, in pandas.index.IndexEngine.get_loc (pandas/index.c:4443)
  File "pandas/index.pyx", line 161, in pandas.index.IndexEngine.get_loc (pandas/index.c:4289)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13733)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13687)
KeyError: 'channelid'

```

**Comment by jlandercy** [comment]
All API works again, noise can now get their data.
